[package]
name = "purrfect_vault"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
bitcoin = "0.31.1"
bitcoin-rpc = "0.2.0"
hex = "0.4.3"
rand = "0.4.6"